version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: petshop
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petshop
    ports:
      - "5429:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./raw_data:/raw_data"

volumes:
  pgdata:
